// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package ecode

import mock "github.com/stretchr/testify/mock"

// MockEcodeRepositorier is an autogenerated mock type for the EcodeRepositorier type
type MockEcodeRepositorier struct {
	mock.Mock
}

// DeleteById provides a mock function with given fields: id
func (_m *MockEcodeRepositorier) DeleteById(id string) (string, error) {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *MockEcodeRepositorier) FindAll() ([]Ecode, error) {
	ret := _m.Called()

	var r0 []Ecode
	if rf, ok := ret.Get(0).(func() []Ecode); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Ecode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *MockEcodeRepositorier) FindById(id string) (*Ecode, error) {
	ret := _m.Called(id)

	var r0 *Ecode
	if rf, ok := ret.Get(0).(func(string) *Ecode); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Ecode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ecode
func (_m *MockEcodeRepositorier) Insert(ecode *Ecode) (*Ecode, error) {
	ret := _m.Called(ecode)

	var r0 *Ecode
	if rf, ok := ret.Get(0).(func(*Ecode) *Ecode); ok {
		r0 = rf(ecode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Ecode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Ecode) error); ok {
		r1 = rf(ecode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ecode
func (_m *MockEcodeRepositorier) Update(ecode *Ecode) (*Ecode, error) {
	ret := _m.Called(ecode)

	var r0 *Ecode
	if rf, ok := ret.Get(0).(func(*Ecode) *Ecode); ok {
		r0 = rf(ecode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Ecode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Ecode) error); ok {
		r1 = rf(ecode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
