// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package ecode

import mock "github.com/stretchr/testify/mock"

// MockEcodeServicer is an autogenerated mock type for the EcodeServicer type
type MockEcodeServicer struct {
	mock.Mock
}

// DeleteById provides a mock function with given fields: id
func (_m *MockEcodeServicer) DeleteById(id string) (*Response, error) {
	ret := _m.Called(id)

	var r0 *Response
	if rf, ok := ret.Get(0).(func(string) *Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllEcodes provides a mock function with given fields:
func (_m *MockEcodeServicer) GetAllEcodes() ([]Response, error) {
	ret := _m.Called()

	var r0 []Response
	if rf, ok := ret.Get(0).(func() []Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEcodeById provides a mock function with given fields: id
func (_m *MockEcodeServicer) GetEcodeById(id string) (*Response, error) {
	ret := _m.Called(id)

	var r0 *Response
	if rf, ok := ret.Get(0).(func(string) *Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ecode
func (_m *MockEcodeServicer) Insert(ecode *Ecode) (*Response, error) {
	ret := _m.Called(ecode)

	var r0 *Response
	if rf, ok := ret.Get(0).(func(*Ecode) *Response); ok {
		r0 = rf(ecode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Ecode) error); ok {
		r1 = rf(ecode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ecode
func (_m *MockEcodeServicer) Update(ecode *Ecode) (*Response, error) {
	ret := _m.Called(ecode)

	var r0 *Response
	if rf, ok := ret.Get(0).(func(*Ecode) *Response); ok {
		r0 = rf(ecode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Ecode) error); ok {
		r1 = rf(ecode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
