# app info
appInfo:
    name: "Viper Config Example"
    description: "Viper configuration example for a Go application"
    version: "1.0.0"

# server port
server:
    host: localhost
    httpPort: ":8080"

database:
    sqlite:
        driver: sqlite3
        dsn: test_dbase.sqlite
    postgres:
        driver: postgres
        dsn: ${DATABASE_POSTGRES_DSN}
    maxIdleConns: 1
    maxOpenConns: 5
    maxIdleTime: 60
