appInfo:
    name: "aConfig Example"
    description: "yaml aconfig example for a Go application"
    version: "1.0.0"

server:
    host: localhost
    httpPort: ":8090"

database:
    sqlite:
        driver: sqlite3
        dsn: ${SQLITE_DSN}
    postgres:
        driver: postgres
        dsn: ${POSTGRES_DSN}
    max_idle_conns: 1
    max_open_conns: 5
    maxIdleTime: 60
