appInfo:
    name: "aConfig Example"
    description: "yaml aconfig example for a Go application"
    version: "1.0.0"

server:
    host: localhost
    httpPort: ":8090"

databases:
    primary:
        driver: sqlite3
        host: localhost
        name: primary_db.sqlite
    secondary:
        driver: postgresql
        host: localhost
        port: 5432
        name: secondary_db
        username: admin
        password: ${PASSWORD}
#        connectionPool:
#            max_idle_connection: 10
#            max_open_connection: 5
#            maxIdleTime: 30

